# Generated by Django 5.2.10 on 2026-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_notification_target_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='share_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
