# Generated by Django 5.2.10 on 2026-03-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='initial_price',
            new_name='price_at_addition',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_url',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(db_column='wishlist_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop_app.wishlist'),
        ),
    ]
