# Generated by Django 5.2.10 on 2026-03-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_notification_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_app.orderitem'),
        ),
    ]
