# Generated by Django 5.2.10 on 2026-03-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0012_cartitem_custom_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='order_item',
            field=models.ForeignKey(db_column='order_item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop_app.orderitem'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order_item', 'stage')},
        ),
    ]
