# Generated by Django 5.2.10 on 2026-03-09 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0013_review_stage_alter_review_order_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('order_item',)},
        ),
        migrations.AlterModelTable(
            name='reviewphoto',
            table='products_review_photo',
        ),
        migrations.CreateModel(
            name='LongTermReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_reply', models.TextField(blank=True, null=True)),
                ('reply_at', models.DateTimeField(blank=True, null=True)),
                ('stage', models.IntegerField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('order_item', models.ForeignKey(db_column='order_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='long_term_reviews', to='shop_app.orderitem')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='shop_app.product')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products_long_term_review',
                'unique_together': {('order_item', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='LongTermReviewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='shop_app.longtermreview')),
            ],
            options={
                'db_table': 'products_long_term_review_photo',
            },
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stage',
        ),
    ]
