# Generated by Django 5.2.10 on 2026-03-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0015_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsetting',
            name='review_invite_on',
            field=models.BooleanField(default=True),
        ),
    ]
