# Generated by Django 5.2.10 on 2026-03-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_notificationsetting_review_invite_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationsetting',
            old_name='review_invite_on',
            new_name='invitation_on',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='order_on',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='promo_on',
        ),
        migrations.RemoveField(
            model_name='notificationsetting',
            name='stock_on',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='order_update_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='price_drop_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='promotion_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='restock_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='master_switch',
            field=models.BooleanField(default=True),
        ),
    ]
