# Generated by Django 5.2.10 on 2026-03-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0017_rename_review_invite_on_notificationsetting_invitation_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_reward_issued',
            field=models.BooleanField(default=False),
        ),
    ]
